import {describe,it,expect,vi} from 'vitest';
import {interpretRoute} from './interpret';
import {FIELD_KEYS} from '../src/proposal';
function request(description='Fixed timber window with aluminium caps.'){const form=new FormData();form.set('description',description);return new Request('https://lithic.test/api/proposals',{method:'POST',headers:{origin:'https://lithic.test'},body:form})}
const extracted={product:'Window',supported:true,reason:'Supported',questions:['What is the depth?'],fields:Object.fromEntries(FIELD_KEYS.map(k=>[k,{value:null,status:'unknown',sourceId:null,evidence:''}]))};
describe('interpretation boundary',()=>{
 it('reports connection state and never calls upstream without a key',async()=>{const upstream=vi.fn();const response=await interpretRoute(request(),{},upstream);expect(response.status).toBe(503);expect(upstream).not.toHaveBeenCalled();expect(await (await interpretRoute(new Request('https://lithic.test/api/interpretation/status'),{})).json()).toEqual({available:false})});
 it('rejects foreign origins and empty descriptions',async()=>{const upstream=vi.fn();const foreign=request();foreign.headers.set('origin','https://evil.test');expect((await interpretRoute(foreign,{OPENAI_API_KEY:'test'},upstream)).status).toBe(403);expect((await interpretRoute(request(''),{OPENAI_API_KEY:'test'},upstream)).status).toBe(400);expect(upstream).not.toHaveBeenCalled()});
 it('sends structured data, keeps credentials server side and returns unknowns',async()=>{let payload:any;const upstream=vi.fn(async(_url:any,init:any)=>{payload=JSON.parse(init.body);return Response.json({status:'completed',output:[{content:[{type:'output_text',text:JSON.stringify(extracted)}]}]})});const response=await interpretRoute(request(),{OPENAI_API_KEY:'test-secret'},upstream as typeof fetch);const body=await response.json();expect(response.status).toBe(200);expect(payload.store).toBe(false);expect(payload.text.format.strict).toBe(true);expect(body.fields.frameDepth.value).toBeNull();expect(body.sources[0].sha256).toHaveLength(64);expect(JSON.stringify(body)).not.toContain('test-secret')});
 it('sends image bytes and source IDs, rejects disguised files',async()=>{const form=new FormData();form.set('description','Fixed timber window');form.append('references',new File([new Uint8Array([137,80,78,71,13,10,26,10])],'drawing.png',{type:'image/png'}));let payload:any;const upstream=vi.fn(async(_url:any,init:any)=>{payload=JSON.parse(init.body);return Response.json({status:'completed',output:[{content:[{type:'output_text',text:JSON.stringify(extracted)}]}]})});const response=await interpretRoute(new Request('https://lithic.test/api/proposals',{method:'POST',headers:{origin:'https://lithic.test'},body:form}),{OPENAI_API_KEY:'test'},upstream as typeof fetch);expect(response.status).toBe(200);expect(payload.input[0].content.find((x:any)=>x.type==='input_image').image_url).toMatch(/^data:image\/png;base64,/);const invalid=new FormData();invalid.set('description','test');invalid.append('references',new File(['wrong'],'bad.png',{type:'image/png'}));expect((await interpretRoute(new Request('https://lithic.test/api/proposals',{method:'POST',headers:{origin:'https://lithic.test'},body:invalid}),{OPENAI_API_KEY:'test'},upstream as typeof fetch)).status).toBe(400)});
 it('handles refusal, invalid evidence, incomplete output and upstream errors',async()=>{for(const body of [{status:'completed',output:[{content:[{type:'refusal'}]}]},{status:'incomplete'},{status:'completed',output:[{content:[{type:'output_text',text:'{}'}]}]}]){const r=await interpretRoute(request(),{OPENAI_API_KEY:'test'},vi.fn(async()=>Response.json(body)) as typeof fetch);expect(r.status).toBeGreaterThanOrEqual(400)}const r=await interpretRoute(request(),{OPENAI_API_KEY:'test'},vi.fn(async()=>new Response('private error',{status:500})) as typeof fetch);expect(await r.text()).not.toContain('private error')});
});
