import {test,expect} from '@playwright/test';
const proposal={id:'proposal-browser-test',revision:1,createdAt:'2026-10-08',model:'test-provider',description:'A fixed timber window with exterior aluminium caps.',product:'Reference window',supported:true,reason:'Single fixed timber window.',questions:['Confirm frame depth.'],sources:[{id:'description',name:'Product description',type:'text/plain',sha256:'test'}],fields:Object.fromEntries(Object.entries({width:1100,height:1400,frameFace:60,frameDepth:null,glazingThickness:32}).map(([key,value])=>[key,{value,status:value===null?'unknown':'stated',sourceId:value===null?null:'description',evidence:value===null?'':'Explicit '+key}]))};
test('proposal flow uses reviewed evidence and invalidates edited approval',async({page},testInfo)=>{
 await page.route('**/api/interpretation/status',route=>route.fulfill({json:{available:true}}));
 await page.route('**/api/proposals',async route=>{expect(route.request().postData()).toContain('Product description');await route.fulfill({json:proposal})});
 await page.goto('/');await page.getByLabel('Product description').fill('Product description: fixed timber window, exterior aluminium caps, 1100 x 1400.');
 await page.getByRole('button',{name:'Create product proposal'}).click();await expect(page.getByRole('heading',{name:'Reference window',exact:true})).toBeVisible();await expect(page.locator('canvas')).toHaveCount(0);
 await expect(page.getByRole('button',{name:'Approve product definition'})).toBeDisabled();await page.getByLabel(/^Frame depth mm$/).fill('110');await page.getByLabel('Source for Frame depth').fill('Confirmed by reviewer from detail A');
 await page.screenshot({path:testInfo.outputPath('source-review.png')});await page.getByRole('button',{name:'Approve product definition'}).click();await expect(page.locator('canvas')).toBeVisible();await expect(page.getByLabel('Width',{exact:true})).toHaveValue('1100');
 await page.getByLabel('Width',{exact:true}).fill('1275');await page.getByLabel('Height',{exact:true}).fill('1625');await expect(page.getByRole('button',{name:'Download build request'})).toBeEnabled();await expect(page.getByRole('alert')).toHaveCount(0);
 const downloadEvent=page.waitForEvent('download');await page.getByRole('button',{name:'Download build request'}).click();const download=await downloadEvent;const stream=await download.createReadStream();let text='';for await(const chunk of stream!)text+=chunk.toString();const data=JSON.parse(text);expect(data.definition.frameFace).toBe(60);expect(data.definition.proposal.fields.frameDepth.evidence).toBe('Confirmed by reviewer from detail A');expect(data.parts.find((p:any)=>p.role==='glazing').size).toEqual([1155,1505,32]);expect(data.configuration.width).toBe(1275);expect(data.configuration.height).toBe(1625);expect(data.definition.proposal.fields.width.value).toBe(1100);expect(data.definition.proposal.fields.height.value).toBe(1400);expect(data.configurationBasis.manufacturerSizeVerified).toBe(false);
 await page.getByRole('button',{name:/Review$/}).click();await page.getByLabel(/^Frame face mm$/).fill('65');await expect(page.getByRole('button',{name:/Configure$/})).toBeDisabled();await expect(page.locator('canvas')).toHaveCount(0);
});
test('service failures do not silently load the fixture',async({page})=>{
 await page.route('**/api/interpretation/status',r=>r.fulfill({json:{available:true}}));await page.route('**/api/proposals',r=>r.fulfill({status:502,json:{error:'Interpretation failed.'}}));await page.goto('/');await page.getByRole('button',{name:'Create product proposal'}).click();await expect(page.getByRole('status')).toContainText('Interpretation failed.');await expect(page.getByRole('button',{name:/Review$/})).toBeDisabled();
});
