import {describe,it,expect} from 'vitest';
import {FIELD_KEYS,validateExtraction,proposalDefinition,proposalIssues,type Proposal} from './proposal';
import {calculateParts,configurationIssues} from './engine';
const proposal:Proposal={id:'test-proposal',revision:1,createdAt:'2026-10-08',model:'test',product:'Fixed timber window',supported:true,reason:'Single fixed timber window with aluminium caps.',description:'test',sources:[{id:'description',name:'Description',type:'text/plain',sha256:'test'}],questions:[],fields:Object.fromEntries(FIELD_KEYS.map(k=>[k,{value:({width:1100,height:1400,frameFace:60,frameDepth:110,glazingThickness:32})[k],status:'stated',sourceId:'description',evidence:`Explicit ${k}`}])) as Proposal['fields']};
describe('source grounded proposals',()=>{
 it('rejects missing evidence and invented sources',()=>{expect(()=>validateExtraction({...proposal,fields:{...proposal.fields,width:{...proposal.fields.width,sourceId:'invented'}}},['description'])).toThrow();expect(()=>validateExtraction({...proposal,fields:{...proposal.fields.width,width:{value:1100,status:'stated',sourceId:null,evidence:''}}},['description'])).toThrow()});
 it('keeps unknown dimensions blocked without sample fallback',()=>{const p={...proposal,fields:{...proposal.fields,frameFace:{value:null,status:'unknown' as const,sourceId:null,evidence:''}}};expect(proposalIssues(p)).not.toHaveLength(0);expect(()=>proposalDefinition(p)).toThrow()});
 it('rejects unsupported products, conflicts and impossible dimensions',()=>{expect(()=>proposalDefinition({...proposal,supported:false})).toThrow();expect(()=>validateExtraction({...proposal,fields:{...proposal.fields,width:{...proposal.fields.width,status:'conflict'}}},['description'])).toThrow();expect(()=>proposalDefinition({...proposal,fields:{...proposal.fields,glazingThickness:{...proposal.fields.glazingThickness,value:150}}})).toThrow()});
 it('resizes using approved profiles without rewriting source evidence',()=>{const {definition,configuration}=proposalDefinition(proposal);expect(calculateParts(definition,configuration).find(p=>p.role==='glazing')?.size).toEqual([980,1280,32]);const resized={...configuration,width:1275,height:1625};expect(configurationIssues(resized,definition)).toEqual([]);expect(calculateParts(definition,resized).find(p=>p.role==='glazing')?.size).toEqual([1155,1505,32]);expect(definition.proposal?.fields.width.value).toBe(1100);expect(definition.proposal?.fields.height.value).toBe(1400);expect(definition.proposal?.sources).toEqual(proposal.sources)});
});
