import { Suspense,useMemo,useState,Component,type ReactNode } from 'react';
import { Canvas } from '@react-three/fiber';
import { OrbitControls,ContactShadows,Html,Line } from '@react-three/drei';
import * as THREE from 'three';
import { calculateParts,type Definition,type Configuration } from './engine';
class SceneBoundary extends Component<{children:ReactNode},{failed:boolean}> {state={failed:false};static getDerivedStateFromError(){return {failed:true}};render(){return this.state.failed?<div className="scene-fallback">3D preview unavailable on this device. Your definition and configuration remain available.</div>:this.props.children}}
function woodTexture(){const canvas=document.createElement('canvas');canvas.width=256;canvas.height=512;const ctx=canvas.getContext('2d')!;ctx.fillStyle='#b99670';ctx.fillRect(0,0,256,512);for(let i=0;i<190;i++){const x=(i*37)%256;ctx.strokeStyle=`rgba(77,47,23,${0.025+(i%7)*0.014})`;ctx.lineWidth=0.5+(i%3);ctx.beginPath();ctx.moveTo(x,0);for(let y=0;y<=512;y+=16)ctx.lineTo(x+Math.sin(y/85+i)*2,y);ctx.stroke()}const tex=new THREE.CanvasTexture(canvas);tex.colorSpace=THREE.SRGBColorSpace;return tex}
function Window({definition,config,section,dimensions}:{definition:Definition;config:Configuration;section:boolean;dimensions:boolean}) {
 const parts=useMemo(()=>calculateParts(definition,config),[definition,config]);const wood=useMemo(woodTexture,[]);const w=config.width/1000,h=config.height/1000;
 return <group position={[0,-h/2,0]}>{parts.filter(p=>!section||!p.id.endsWith('right')).map(p=><mesh key={p.id} position={p.position.map(n=>n/1000) as [number,number,number]} castShadow receiveShadow><boxGeometry args={p.size.map(n=>n/1000) as [number,number,number]}/>{p.role==='glazing'?<meshPhysicalMaterial color="#b5c5c2" transparent opacity={0.28} roughness={0.06} metalness={0.1} side={THREE.DoubleSide}/>:<meshStandardMaterial map={p.role==='timber'&&config.interior==='timber'?wood:null} color={p.role==='timber'?(config.interior==='white'?'#e7e5de':'#dbc3a4'):(config.exterior==='white'?'#d9dcd6':'#3c4240')} roughness={p.role==='timber'?0.72:0.34} metalness={p.role==='aluminium'?0.65:0}/>}</mesh>)}
 {dimensions&&<><Line points={[[-w/2,-0.1,0.13],[w/2,-0.1,0.13]]} color="#757d77" lineWidth={1}/><Line points={[[-w/2,-0.13,0.13],[-w/2,-0.06,0.13]]} color="#757d77"/><Line points={[[w/2,-0.13,0.13],[w/2,-0.06,0.13]]} color="#757d77"/><Html center position={[0,-0.18,0.13]}><span className="dimension-label">{config.width} mm</span></Html><Line points={[[-w/2-0.13,0,0.13],[-w/2-0.13,h,0.13]]} color="#757d77"/><Html center position={[-w/2-0.21,h/2,0.13]}><span className="dimension-label vertical">{config.height} mm</span></Html></>}
 <ContactShadows position={[0,-0.005,0]} opacity={0.35} scale={6} blur={2.8} far={2}/></group>
}
export default function WindowScene(props:{definition:Definition;config:Configuration;section:boolean;dimensions:boolean}) {
 const [lost,setLost]=useState(false);return <SceneBoundary>{lost?<div className="scene-fallback">Graphics context lost. Reload to restore the preview.</div>:<Canvas shadows dpr={[1,2]} camera={{position:[1.5,0.6,3.4],fov:34}} onCreated={({gl})=>gl.domElement.addEventListener('webglcontextlost',()=>setLost(true))}><color attach="background" args={['#eeede7']}/><ambientLight intensity={1.5}/><directionalLight position={[3,5,4]} intensity={3} castShadow/><directionalLight position={[-3,2,-2]} intensity={1}/><Suspense fallback={null}><Window {...props}/></Suspense><OrbitControls makeDefault minDistance={2} maxDistance={6} target={[0,0,0]} enablePan={false}/></Canvas>}</SceneBoundary>
}
